docs: 프로미스 심층 연습 노트에 예시코드 추가
ono212/rumicube pull request #1
Opened 2023-05-19 14:39 UTC by ono212

## 배경

- 지난 피드백에 따라 설명을 더 쉽게 이해할 수 있도록 예시코드를 추가합니다.

2023-05-20 08:11 UTC, datalater requested changes
수고했어요! 좀 더 쉬운 글이 될 수 있는 제안을 남겼습니다.

제안한 내용 반영하면 approve 하겠습니다 👍

2023-05-22 12:12 UTC, datalater reviewed
나중에 잊지 말고 추가해야 할 사항을 제안했고 다 삭제할 필요가 없어보이는 변경에 대해 질문을 남겼습니다. 확인 부탁드려요🙂

2023-05-27 19:07 UTC, ono212 commented on deep-practice/promise.md
> +> 생성할 때 프라미스 객체의 `state`프로퍼티는 `pending`, `result`프로퍼티는 `undefined`입니다. 그리고 객체를 생성하면서 `executor`라는 실행함수를 인자로 넘깁니다. `executor`는 `new Promise`로 생성할 때 바로 실행됩니다. 이 실행함수에 비동기로 처리할 작업을 작성합니다. 이 실행함수의 구조는 어느
반영했습니다! 감사해요! 문장이 길어지면 끊어서 작성해보도록 앞으로는 신경 써보겠습니다!

2023-05-27 19:09 UTC, ono212 commented on deep-practice/promise.md
>  Q. 프라미스로 어떻게 비동기 처리를 할 수 있나요?
앗,,탈주는 안되는데...
반영했습니다. 이렇게 하니 눈에 더 잘들어오네요..!! 좀 더 개발자의 입장에서 읽기 쉬운 흐름으로 쓰도록 노력해보겠습니다~!

2023-05-27 19:12 UTC, ono212 commented on deep-practice/promise.md
> -> 먼저 프라미스는 `new Promise(executor)`로 프라미스 객체를 생성할 수 있습니다. 생성할 때 프라미스 객체의 `state`프로퍼티는 `pending`, `result`프로퍼티는 `undefined`입니다. 그리고 객체를 생성하면서 `executor`라는 실행함수를 인자로 넘깁니다. `executor`는 `new Promise`로 생성할
제가 생각하기에 앞의 댓글에서 제안해주신 내용과 겹치는 부분은 빼고 뒤에서 두개의 문장은 살려두었는데, 다음 스터디 시간에 다시 얘기해보면 좋을 것 같아요!

2023-05-27 19:13 UTC, ono212 commented on deep-practice/promise.md
> +```
앗 네! 좀 더 finally의 의도에 맞는 그런 멋있는 실전 예시를 추가해보도록 하겠습니다!😎

2023-05-28 03:08 UTC, datalater commented on deep-practice/promise.md
>  Q. 프라미스로 어떻게 비동기 처리를 할 수 있나요?
네 배우는 자세 아주 좋습니다💯

2023-05-28 03:12 UTC, datalater reviewed
promise-tasks.md 파일에서 3번째 과제는 작성 중이라고 되어 있더라고요. 요거 해명(?) 해주시면 바로 어푸르브할게요 😉

2023-05-28 03:12 UTC, datalater commented on deep-practice/promise-tasks.md
> +> 작성 중,,,
여기는 아직 작성 중인가요?👀

2023-05-28 12:14 UTC, ono212 commented on deep-practice/promise-tasks.md
> +> 작성 중,,,
문제의 코드가 길어서 어느 부분부터 설명해야할지 작성하면서 고민이 됐었어요,,~! 지금 작성해서 올렸습니다!

2023-05-28 16:43 UTC, datalater approved these changes
수고 많았어요 승인합니다 머지 가즈아🚀

2023-05-28 16:43 UTC, datalater commented on deep-practice/promise-tasks.md
> +> [동작을 확인할 수 있는 샌드박스 링크입니다.](https://plnkr.co/edit/eAP9wNrKyu2LvWLZ?p=preview&preview)
샌드박스 링크까지 친절하게 달아주셨군요. 완전 굿입니다 👍 앞으로도 이렇게 세심하게 적어주세요 😉

2023-05-29 23:04 UTC, datalater commented
머지하세요~~

2023-05-30 13:33 UTC, merged