docs: 프로미스와 에러 핸들링 심층 연습 노트 추가
ono212/rumicube pull request #4
Opened 2023-06-02 20:12 UTC by ono212

# 어떤 내용이었는지 요약해주세요.

- `catch` 메서드를 사용하면 프로미스의 에러를 쉽게 핸들링할 수 있습니다.

# 이번 학습을 통해 본인에게 무엇이 달라졌나요?

- 프로미스 체인에서 `catch` 메서드를 사용하여 프로미스의 에러를 핸들링할 수 있습니다.
  - `catch` 메서드는 자신보다 상위에 있는 프로미스에서 발생하는 에러만 감지합니다.
  - 그렇기 때문에 적당한 위치에 적절한 에러 핸들링 코드를 작성하는게 중요하다는 점을 알게 되었습니다. 
- `unhandledrejection` 이벤트가 언제 사용되는지 이해했습니다.
  - 프로미스에서 에러가 발생했는데 에러 핸들러가 없다면 `unhandledrejection` 이벤트가 발생합니다.
  - 그래서 해당 이벤트에 대한 이벤트 리스너를 작성하여 이런 상황을 처리할 수 있습니다.

# 여전히 잘 모르겠거나 궁금한 점을 모두 적어주세요.
- 더 추가하면 좋은 내용이 있을까요?

# 보완할 점

- 작성한 것들에 대해 예시 코드를 추가하려고 합니다.
- 모자튜에 있는 `setTimeout`의 콜백에서 `throw error`를 할 경우 `catch`가 트리거되지 않는 예제에 대해서 작성하려고 합니다.

2023-06-09 01:12 UTC, datalater requested changes
문장을 두괄식으로 적도록 제안했습니다. 확인 후 반영 부탁드려요 😄

2023-06-09 01:12 UTC, datalater commented on deep-practice/promise-error-handling.md
> +> 에러가 발생하면 가장 가까운 에러 핸들러를 실행합니다. 즉 가장 가까운 `then`의 `rejection`핸들러나 `catch`의 핸들러를 실행합니다. 이 핸들러 내부에 에러를 어떻게 처리할지 코드를 작성하면 됩니다.
[제안]

질문에 대한 답변은 최대한 두괄식으로 적어주세요. 

```suggestion
Q. 프로미스에서 에러가 발생하면 어떻게 처리할 수 있나요?

> 가장 가까운 `then`의 `rejection`핸들러나 `catch`의 핸들러를 추가하고 이 핸들러 내부에 에러를 어떻게 처리할지 코드를 작성하면 됩니다. 왜냐하면 에러가 발생하면 가장 가까운 에러 핸들러를 실행하기 때문입니다.
```

현재 문장과 제안 문장은 문장의 나열 순서에서 차이점이 있습니다.

현재 문장:

1. Q. 프로미스에서 에러가 발생하면 어떻게 처리할 수 있나요?
2. 에러가 발생하면 가장 가까운 에러 핸들러를 실행합니다. 

위에서는 질문에 대한 답변이 바로 등장한 게 아니라 답변에 대한 전제가 먼저 등장했습니다. "어떻게 해야 돼?"라고 물어봤는데 "일단 전제부터 들어봐"라고 답변한 셈입니다.

제안 문장:

1. Q. 프로미스에서 에러가 발생하면 어떻게 처리할 수 있나요?
2. 가장 가까운 `then`의 `rejection`핸들러나 `catch`의 핸들러를 추가하고 이 핸들러 내부에 에러를 어떻게 처리할지 코드를 작성하면 됩니다.

여기서는 질문에 대한 답변인 어떻게 해야 하는지부터 바로 등장합니다. 첫문장에서 질문에 대한 답변을 바로 얻을 수 있습니다. 답변부터 두괄식으로 하고 전제는 뒤에서 등장합니다.

---

[기대효과]

말과 글에서 두괄식으로 이야기하는 방식이 습관화되면 면접이나 실무에서 의사소통할 때 상대방이 원하는 내용을 먼저 얘기하여 소통을 더 원활하게 할 수 있습니다. 두괄식으로 이야기하는 연습도 꾸준히 해서 습관화 합시다!

2023-06-09 01:27 UTC, datalater commented on deep-practice/promise-error-handling-tasks.md
> +# 프로미스와 에러 핸들링 과제
여기도 모자튜 아티클 링크를 달아주세요.

참고로 섹션 제목 같은 경우 hash 링크(`#tasks`)를 달면 됩니다:

```suggestion
# [프로미스와 에러 핸들링 과제](https://ko.javascript.info/promise-error-handling#tasks)
```

2023-06-09 01:27 UTC, datalater commented on deep-practice/promise-error-handling-tasks.md
> +> 에러는 호출자 방향으로 전파되는데, `setTimeout`의 콜백함수 같은 경우는 콜 스택의 가장 아래에 위치하기때문에 에러를 전파할 호출자가 없다고 알고 있습니다. 이와 관련된 이유인지 궁금합니다.
reject일 때 캐치되는 이유는 promise가 이행되었기 때문이고, reject가 아닌 비동기 콜백에서 throw error를 한 경우는 promise가 이행되지 않았기 때문에 catch 되지 않습니다.

2023-06-09 01:44 UTC, datalater commented on deep-practice/promise-error-handling-tasks.md
> +> 에러는 호출자 방향으로 전파되는데, `setTimeout`의 콜백함수 같은 경우는 콜 스택의 가장 아래에 위치하기때문에 에러를 전파할 호출자가 없다고 알고 있습니다. 이와 관련된 이유인지 궁금합니다.
> 에러는 호출자 방향으로 전파되는데, `setTimeout`의 콜백함수 같은 경우는 콜 스택의 가장 아래에 위치하기때문에 에러를 전파할 호출자가 없다고 알고 있습니다. 이와 관련된 이유인지 궁금합니다.

네 이것과 동일한 이유가 맞는 것 같습니다

2023-06-10 05:22 UTC, ono212 commented on deep-practice/promise-error-handling-tasks.md
> +> 에러는 호출자 방향으로 전파되는데, `setTimeout`의 콜백함수 같은 경우는 콜 스택의 가장 아래에 위치하기때문에 에러를 전파할 호출자가 없다고 알고 있습니다. 이와 관련된 이유인지 궁금합니다.
그럼 `throw error`를 하면 promise는 어떤 상태인가요? pending상태인가요??

2023-06-10 05:24 UTC, ono212 commented on deep-practice/promise-error-handling.md
> +> 에러가 발생하면 가장 가까운 에러 핸들러를 실행합니다. 즉 가장 가까운 `then`의 `rejection`핸들러나 `catch`의 핸들러를 실행합니다. 이 핸들러 내부에 에러를 어떻게 처리할지 코드를 작성하면 됩니다.
두괄식이 더 전달이 잘 되는 것 같아요~~ 두괄식으로 써보도록 신경써서 쏘볼게요~! 하핫!🐮

2023-06-10 05:25 UTC, ono212 commented on deep-practice/promise-error-handling.md
> +- [catch메서드 체이닝 예제 코드](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Using_promises#chaining_after_a_catch)
하핫 감사합니다!🥴

2023-06-10 05:26 UTC, ono212 commented on deep-practice/promise-error-handling.md
> +# 프로미스와 에러 핸들링
아유 그러게요~~!이제부터 꼭 같이 작성해야겠어요~!

2023-06-10 05:28 UTC, ono212 commented on deep-practice/promise-error-handling-tasks.md
> +# 프로미스와 에러 핸들링 과제
하핫 링크를 꼭 함께 작성하는 습관을 들여야겠어요~~!🐱‍🚀

2023-06-17 14:37 UTC, datalater approved these changes
잘했어요! 머지해도 됩니다 😄 🫱🏻

2023-06-18 05:54 UTC, ono212 commented
> 

🫲🏻 감사합니다~~머지~~

2023-06-18 05:55 UTC, merged